---
- name: Configurar el servidor controlador de Ansible
  hosts: controller
  become: yes
  vars_files:
    - ../roles/configurar_controlador/vars/main.yml

  roles:
    - configurar_controlador
  
  post_tasks:
    - name: "âœ… CONFIGURACIÃ“N FINALIZADA CON Ã‰XITO"
      debug:
        msg: |
          ðŸŽ¯ El nodo controlador ya estÃ¡ listo.
          â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          Usa:
              ansible --version
              ansible-inventory --list
              ansible all -m ping
          para probar la instalaciÃ³n.