---
- name: Configurar DHCPv6 en el controlador
  hosts: controller
  become: yes
  roles:
    - role: configurar_dhcpv6_server
      vars:
        iface_lan: "ens37"                 # cambia a tu NIC LAN real
        ipv6_prefix: "2025:db8:20::/64"
        controllpv6: "2025:db8:20::1"
        pool_start: "2025:db8:20::100"
        pool_end:   "2025:db8:20::200"
        dns_servers: ["2025:db8:20::1"]     # o el DNS que prefieras
        domain_search: "lab.local"
        enable_ddns: false                  # dÃ©jalo en false si no usarÃ¡s DDNS
  
  post_tasks:
   - name: "âœ… CONFIGURACIÃ“N FINALIZADA CON Ã‰XITO"
     debug:
       msg: |
          ðŸŽ¯ El nodo controlador ya estÃ¡ listo.
          â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          Usa:
              ansible --version
              ansible-inventory --list
              ansible all -m ping
          para probar la instalaciÃ³n.