---
# =====================================================
# ğŸš€ Bootstrap y verificaciÃ³n de VMs del laboratorio
# =====================================================

- name: ğŸ§  VerificaciÃ³n y preparaciÃ³n mÃ­nima de todos los nodos
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - verificar_requisitos_VMS
